#!/usr/bin/env bash
#transfer a file from client to server
if [ $# -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
server_ip=$2
username=$3
path_of_key=$4

export SCP_OPTIONS="-o StrictHostKeyChecking=no"
scp -i "$path_of_key" "$file_path" "$username@$server_ip:~/"
