#!/usr/bin/env bash
#install nginx web server
apt-get -y update
apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start
