#!/usr/bin/env bash
# display a time
hours=0
while [ $hours -lt 12 ]
do
    echo "Hour: $hours"
    minutes=1
    while [ $minutes -lt 60 ]
    do
        echo $minutes
        minutes=$((minutes+1))
    done

    hours=$((hours+1))
done