#!/usr/bin/env bash
#change home ip address
sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/^127.0.0.1 localhost$/127.0.0.1 localhost\n127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^157.240.11.35 facebook.com$/8.8.8.8 facebook.com/' /etc/hosts