#!/usr/bin/env bash
#change home ip address
cp /etc/hosts /etc/hosts.bak
sed -i 's/^127.0.0.1 localhost$/127.0.0.1 localhost\n127.0.0.2 localhost/' /etc/hosts
sed -i '$ a\ 8.8.8.8 facebook.com' /etc/hosts